import Layout from "@/components/layout/layout";
import "@/styles/globals.css";

export const metadata = {
  title: "Site.Set",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-br">
      <head>
        <link rel="shortcut icon" href="/app-favicon.svg" type="image/svg" />
      </head>
      <body>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
